repos:
  - repo: local
    hooks:
      - id: lint-and-format
        name: Lint and Format Code
        description: Run linters and formatters on the codebase
        entry: make lint-and-format
        language: system
        pass_filenames: false
        stages: [pre-commit, pre-push]
      - id: check-type
        name: Check type
        description: Run type checker on the codebase
        entry: make check-type
        language: system
        pass_filenames: false
        stages: [ pre-commit, pre-push ]
      - id: test-unit
        name: Unit test
        description: Run unit tests
        entry: make test-unit
        language: system
        pass_filenames: false
        stages: [ pre-commit, pre-push ]